### PR TITLE
Merge develop into production

### PR DESCRIPTION
**Pull request by Sixstring982**
This change merges existing changes from develop into production, in hopes of deleting all other branches once this is in.

### CODE REVIEW

**Review by paul-perez — COMMENTED** [review]
This code is not ready for primetime as it is mostly placeholder code.  I recommend that I work with Samina to get basic pages updated according to her wireframes, then when it is ready we push to production.

**Comment by Sixstring982** [comment]
I don't feel that this should be blocked because it contains placeholder code, this is essentially the same as what's in production today. We should merge this in soon so we can fix the branching structure, since it won't affect how prod looks.

**Comment by paul-perez** [comment]
There is an automated CI/CD pipeline on production. Anything checked into production is deployed to production.

**Comment by Sixstring982** [comment]
Yes I understand that, I guess what I'm trying to say is that this change really doesn't affect what's on production. The deployment will look and act the same whether or not we merge this in, because this PR hardly contains anything.

The advantage of merging this in soon is that we can get rid of the big discrepancy between develop and production, and start using feature branches, which is where you and Samina should start getting rid of placeholders.

**Review by paul-perez — APPROVED** [review]
ok for production.

**Pull request merged**
